<h1>Estados</h1>

<?php $this->mensagem(); ?>

<p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p>

<table border="1">
  <thead>
    <tr>
      <td>#</td>
      <td>Estado</td>
      <td>Sigla</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->estados as $estado) { ?>
        <tr>
          <td><?php echo $estado['idestado']; ?></td>
          <td><?php echo $estado['nome_estado']; ?></td>
          <td><?php echo $estado['sigla_estado']; ?></td>
          
          <td>
            [<a href="<?php echo $this->url(array('action' => 'update', 'idcategoria' => $categoria['idcategoria'])); ?>">editar</a>]
            [<a href="<?php echo $this->url(array('action' => 'delete', 'idcategoria' => $categoria['idcategoria'])); ?>">apagar</a>]
          </td>
        </tr>
    <?php } ?>
  </tbody>
</table>