<p>Bem vindo, <?php echo $this->usuario ?></p>

<h1>Estados</h1>
<h2>Ao clicar em algum estado, todas as cidades relacionadas ao estado devem ser exibidas</h2>
<ul>
    <?php foreach ($this->estados as $estado) { ?>
      <li>
        <a href="<?php echo $this->url(array('action' => 'estado', 'idestado' => $post['idestado'])); ?>">
            <?php echo $estado['sigla_estado'] ?> - <?php echo $estado['nome_estado'] ?>
        </a>
      </li>
  <?php } ?>
</ul>

<h1>Cidades</h1>
<h2>As ações de apagar e editar não estão funcionando ainda</h2>
<table border="1">
    <?php foreach ($this->cidades as $cidade) { ?>
      <tr>
          <td><?php echo $cidade['sigla_estado'] ?></td>
          <td><?php echo $cidade['nome_cidade'] ?></td>
          <td><?php echo $cidade['populacao'] ?></td>
          <td><a href="<?php echo $this->url(array(
                'action' => 'cidade', 
              'idcidade' => $cidade['idcidade'])); ?>">Editar</a></td>
          <td><a href="<?php echo $this->url(array(
                'action' => 'cidade', 
              'idcidade' => $cidade['idcidade'])); ?>">Apagar</a></td>
            
      </tr>
  <?php } ?>
</table>